version: '3.8'

services:
  mysql:
    image: mysql:8.0.42
    container_name: my-mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_USER=myuser
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    image: mattan41/unseenservant-backend:latest
    container_name: my-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      FRONTEND_URL: https://unseenservant.se
      GITHUB_ID: ${GITHUB_ID}
      GITHUB_SECRET: ${GITHUB_SECRET}
      GOOGLE_ID: ${GOOGLE_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      FILE_UPLOAD_DIR: /app/uploads/character-images
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - uploads-data:/app/uploads/character-images

  nginx:
    image: mattan41/unseenservant-frontend:latest
    container_name: my-nginx
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: my-cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}

volumes:
  mysql-data:
  uploads-data: