spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.docker.compose.file=compose.yaml

FRONTEND_URL=http://localhost:5173
ALLOWED_ORIGINS=http://localhost:5173,http://localhost:5174

file.upload-dir=${FILE_UPLOAD_DIR:./uploads/character-images}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# SQL Script Initialization,
# change to 'always' if you want to initialize the database on startup
# 'never' if you want to initialize the database manually
spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:demo-data.sql


# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

# User whitelist
ADMIN_WHITELIST=${ADMIN_WHITELIST}
USER_WHITELIST=${USER_WHITELIST}

# OAUTH
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.github.client-id=${GITHUB_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

# OAUTH Redirects
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:8080/login/oauth2/code/github

# Logging
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.web.cors=DEBUG
