# Docker Compose
spring.flyway.enabled=false
spring.docker.compose.enabled=false
# H2 In-Memory Database Configuration
spring.datasource.url=jdbc:h2:mem:unseenservantdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

file.upload-dir=${FILE_UPLOAD_DIR:./uploads/character-images}

# SQL Configuration
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:demo-data.sql

# Frontend Configuration
FRONTEND_URL=http://localhost:5173
ALLOWED_ORIGINS=http://localhost:5173,http://localhost:5174

# User whitelist
ADMIN_WHITELIST=admin@demo.se
USER_WHITELIST=user@demo.se

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000
