# Connect to the docker container mysql
spring.datasource.url=jdbc:mysql://mysql:3306/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret

server.address=0.0.0.0
server.port=8080


# Use this for local development with docker-compose and nginx
FRONTEND_URL=http://localhost

# OAUTH Redirects - use these when running locally with docker-compose and nginx
# spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
# spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:8080/login/oauth2/code/github

# OAUTH Redirects when tunneling from UnseenServant.se, remember to change the redirect URI in GitHub - Google has both
spring.security.oauth2.client.registration.google.redirect-uri=https://unseenservant.se/login/oauth2/code/google
spring.security.oauth2.client.registration.github.redirect-uri=https://unseenservant.se/login/oauth2/code/github
