# Connect to the docker container mysql
spring.datasource.url=jdbc:mysql://mysql:3306/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret

# Run ao all interfaces (Nginx/docker)
server.address=0.0.0.0
server.port=8080

# FRONTEND_URL=https://unseenservant.se
FRONTEND_URL=http://localhost

# OAUTH Redirects - change when deploying to domain UnseenServant.se, remember to change the redirect URI in Google and Github
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:8080/login/oauth2/code/github
