spring.application.name=backend
spring.jpa.hibernate.ddl-auto=update
spring.main.banner-mode=off
spring.jpa.open-in-view=false

USER_WHITELIST=eriksson.nova@gmail.com,knishopf@gmail.com,mats.kruskopf@gmail.com,mats.kruskopf.eriksson@iths.se,krishopf@gmail.com,mats.fpoksurk@gmail.com,user1@example.com,user2@example.com,user3@example.com
ADMIN_WHITELIST=admin@admin.se,mats.kruskopf@gmail.com
file.upload-dir=./uploads/character-images
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# OAUTH
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.github.client-id=${GITH_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITH_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email